### ISSUE TITLE
Designing PCBs and cases for the project demonstration in the physical world

### ISSUE THREAD

**Issue by woswos** [A5-015/ramen#11]
I think it would be really cool if we go completely wireless in the final prototype for demonstrating the project (related issue #6). Otherwise, there will be many micro USB power cables connected to ESP8266s. It would look bad and kinda against our low-power consumption ideal/metric.  

So, we can design a simple PCB with a few buttons, LEDs, 2xAA battery holder, and female pins for plugging an ESP8266 (and maybe even a small OLED screen?). Later, we can 3D print really simple cases for each of these "node"s.

**Comment by niniack** [comment]
- [x] Component selection in conjunction with JLCPCB
- [x] Schematic design
- [x] PCB Routing
- [x] Logistics handling w/ capstone organizers
- [ ] Design case for PCB
- [ ] Print case for PCB

**Comment by niniack** [comment]
https://oshwlab.com/ramen_capstone/demonstration_board_copy

**Comment by woswos** [comment]
Since we decided not to design cases, this issue is completed!
