### ISSUE TITLE
Find simulators

### ISSUE THREAD

**Issue by woswos** [A5-015/ramen#20]
- [x] Understand what to simulate
- [x] Find a simulator for mesh networking
- [x] Find a simulator for consensus algorithms

_A subcomponent of #13_

**Comment by woswos** [comment]
Found it! The [Coracle](https://github.com/consensus-oracle/coracle) can simulate both raft and different types of networks at the same time.

**Comment by niniack** [comment]
For a rainy day, might be worth checking out [Paxi](https://github.com/ailidani/paxi)
