### ISSUE TITLE
Create a script to generate simulation input

### ISSUE THREAD

**Issue by woswos** [A5-015/ramen#22]
The simulation input for Coracle in JSON format.

**Comment by niniack** [comment]
[Completed a basic script to generate simulation input](https://github.com/A5-015/ramen/blob/master/simulation/scripts/sim_config_json.py)

Still adding functionalities: see issues #28 and #30

**Comment by niniack** [comment]
[Modelling of the networks was done in network_generator.py](https://github.com/A5-015/ramen/blob/master/simulation/scripts/network_generator.py)

Thanks @woswos
