### ISSUE TITLE
Finalize and meet the rubric expectations for the final report

### ISSUE THREAD

**Issue by niniack** [A5-015/ramen#76]
**Abstract**
- [x] Captures the bigger picture effectively

**Project Management**
- [x] Work Breakdown Structure: captures more than 2 levels of work other than high level
- [x] DSM shows sequence of tasks with tasks that cause issues
- [x] Critical path path correctly calculated
- [x] Gantt chart captures changes in the project

**Problem Definition**
- [x] Problem Analysis: answers more than standard set of questions
- [x] Black-box Modeling: more than one black box model
- [x] Problem Statement: specs/constraints in quantitative terms

**Conceptualization**
- [x] Background research: Addresses all of the blocks of black box model
- [x] Concept Generation: Generates 3 or more concepts

**Modeling, Simulation, Experimentation & Optimization**
- [x] Modeling/experiment done as per plan, changes suggested and experiment/modeling performed with the changes
- [x] Performs optimization, interprets and verifies results [Adjust heart beat period and time to election timeout parameters in Coracle to find optimal pairing and compare against real world]

**Final Design**

- [x] Initial design proposed: includes initial design, self explanatory documentation
- [x] Changes made: Identifies changes made and why

**Budget**
- [x] Complete bill of materials 

**Implementation Details**
- [x] Description of how successful it has been to implement proposed design: proper description with suggestions for improvement
- [x] Issues faced during implementation/experiments: Identifies issues and why it happens with solutions
- [x] Changes made during implementation: Identifies the changes made with justifications
- [x] Initial Results: recorded and explained

**Ethics**
- [x] Includes ethics and discusses solutions to the issues

**Impact of COVID-19**
- [x] Give information on original scope and reduced or no change in scope

**Did the design meet the requirements?**
- [x] Criteria for testing: appropriate criteria with justifications 
- [x] Test data: recorded appropriately and interpreted effectively
- [x] Discussion on testing data: discusses how the test data meets the requirements; identifies some aspects that need improvement

**Comment by niniack** [comment]
- [x] Add a section about networking library under problem clarification [BARKIN]
- [x] Add suggestions for improvement into implementation successes section
- [x] Update initial results with new figures including logs and description
- [x] Expand the virtual mesh section in mod-sim file
- [x] Write the Criteria for testing subsection in Design Eval section [NISHANT]
- [x] Write the test data and discussion on test data subsesction in Design Eval section [TOGETHER]
- [x] Write results subsection for simulation section
- [x] Check if all figures have comas (like in between left and right)\
- [x] Create new function for testing network stability [BARKIN]
- [x] Create new function for checking average time to first leader (see issue #78) [BARKIN]

Professor Jabari Feedback:
- [x] In `Concept Selection` > "Can you add a couple of sentences describing how to read Pugh charts? This will make the report more self contained. Pugh charts are well known to your capstone course instructors, but not the general reader. Try to address the general reader." [NISHANT]

**Comment by woswos** [comment]
Is `section 5.3 simulation` empty on purpose? - solved
